### ISSUE TITLE
Not compatible with Apple silicon?

### ISSUE THREAD

**Issue by tomkail** [EnvelopSound/EnvelopForLive#100]
Hey! Getting this when opening on an M1 Mac. Is this known?

**Comment by mcslee** [comment]
Hi Tom - I’m not seeing any attachment or error message included here, but
it is a known issue that E4L is not yet updated to max Silicon native, and
still requires running under Rosetta.

It’s top of the list for us to release an update addressing this soon.

Thanks!

**Comment by majogtz** [comment]
https://help.ableton.com/hc/en-us/articles/4415807634322

**Comment by mcslee** [comment]
Apologies it has taken such a long time, but we now have a new release out which supports Apple Silicon: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.3.11
