### ISSUE TITLE
E4L Export Utility missing

### ISSUE THREAD

**Issue by princenifty** [EnvelopSound/EnvelopForLive#101]
Perhaps Im missing something obvious, but I cannot for the life of me figure out where to locate the export utility for the  os x package

**Comment by mcslee** [comment]
Hi there - this is not yet part of the release package. But you can download the AMXD file for this utility directly here:
https://github.com/EnvelopSound/EnvelopForLive/raw/master/devices/E4L%20Export%20Utility.amxd
