### ISSUE TITLE
Add instructions for Windows 

### ISSUE THREAD

**Issue by guiray** [EnvelopSound/EnvelopForLive#14]
There is a way to make E4L work on Windows:

### In short
* Use JackAudio with an external sound card
* Run EVERY software in 32-bits as Admin

### Required Hardware
* External sound card (JackAudio seems to have trouble talking to the system output while using Asio4all)

### Required Software
* Ableton Live Suite 9 32-bits (with max for live)
* Max 32-bits 
* [JackAudio](http://www.jackaudio.org/downloads/) 32 bits
* E4L

### Setup
Follow this JackAudio tutorial for installation but instead of 64-bits, use the 32-bits version: https://www.youtube.com/watch?v=zzd7naKzRgw&index=41&list=WL
Here is some additionnal information for installation: http://www.jackaudio.org/faq/jack_on_windows.html

When setting up the Target of the shortcut (see tutorials), use your external sound card driver.
ex: `C:\Program Files (x86)\Jack\jackd.exe" -R -S -d portaudio -d "ASIO::AudioBox ASIO Driver"`

After that it is pretty much the same as the [Guide](https://docs.google.com/document/d/1tc7bz0knWdPXBOBOPNuQGxPoIH_2_uSd34pQ7NT6d4U/edit)

**RUN EVERYTHING AS ADMIN!**

--
I think i'm not missing anything. There you have it!

I'll be more than happy to answer questions if it is unclear
tested on a Windows 8.1 64-bits machine with a Presonus Audiobox usb sound card

**Comment by guiray** [comment]
Oh! The reason why it is not working with 64 bits applications is because some Max objects (like odot) are only working on the 32 bits version of max.

**Comment by Silkynight** [comment]
Thank. Will test.

Cordially

.

**Comment by roddylindsay** [comment]
Added to guide.  Thanks @guiray!
