### ISSUE TITLE
why not windows 64-bit?

### ISSUE THREAD

**Issue by elsueno** [EnvelopSound/EnvelopForLive#17]
hi there!

thanks for this project! it looks really good.
i'm wondering what needs to be done to make it work with the 64-bit versions of ableton and max on windows...

cheers!

**Comment by guiray** [comment]
Hello!

It is because the some objects in Max are only working with Windows 32-bit.  see #14 's issue for more info.

Cheers!

**Comment by ramagottfried** [comment]
hey -- just a note that odot is built for win64 now, so we might be able to add that to the E4L package -- here is the test build for odot if anyone would like to give it a test run: https://github.com/CNMAT/CNMAT-odot/releases/tag/v1.2-19_windows_beta

cheers,
rama

**Comment by mcslee** [comment]
Hi @guiray - just letting you know that we are now releasing a new version of the software for Live 10. This version should be compatible with Windows 64-bit, and the ODOT externals for Windows 64 are now available in this folder: https://github.com/EnvelopSound/EnvelopForLive/tree/master/externals/CNMAT-odot
