### ISSUE TITLE
Envelop for Live: envelop.maxproj - Errors in Max Console Window

### ISSUE THREAD

**Issue by kingsree** [EnvelopSound/EnvelopForLive#19]
Hello there, 

I'm new to using Envelop for Live - I've followed the User and Developer Guide to the letter, but I keep coming up with the same error in the Max Console Window: "bind to port 4444 unsuccessful".

Any idea what might be causing this issue?

My system is: Macbook Pro 2.7GHz i7, OSX 10.10.5, Max 7.3.4, Live 9.7.3

Any help is appreciated!

Many thanks,

Kingsley

<img width="1440" alt="screen shot 2017-08-22 at 16 43 25" src="https://user-images.githubusercontent.com/30855697/29552628-74effaca-875b-11e7-8ee0-b9b0a7d056bb.png">

**Comment by mcslee** [comment]
It's possible that some other application on your machine is already using port 4444.

If you're comfortable using the Terminal in OS X, you could try following the procedure detailed on this answer to see if you can determine what application might be using that port:
https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x

Alternatively, you can try changing the "4444" to some other port number, and see if that works. You would want to do this in *both* the client and the server windows. Let us know if that works!

**Comment by kingsree** [comment]
Hello Mark,

Thanks so much for responding to my query so swiftly - changing the numbers
in the port worked!

The software is fantastic - thank you so much for your time and efforts, I
appreciate it.

All the best,

Kingsley
