### ISSUE TITLE
Port to Bitwig?

### ISSUE THREAD

**Issue by thommc** [EnvelopSound/EnvelopForLive#27]
This looks fantastic.  Any plans to support Bitwig Studio as well?

**Comment by mcslee** [comment]
Would love to in theory! But unfortunately these tools are all built with Max and therefore depend upon Max for Live. For Bitwig or other DAWs we would have to use VST plugins and also wouldn't have the ability to automate the multi-channel routing as we do with Max for Live.

So unfortunately this is unlikely to happen anytime soon, but it's on our wishlist as well!
