### ISSUE TITLE
Panner has multiple "Spread" parameters

### ISSUE THREAD

**Issue by nyboer** [EnvelopSound/EnvelopForLive#33]
The device "E4L Source Panner" has several number boxes with the _short name_ of **Spread**. I noticed that the _scripting name_ has a unique name, and perhaps that is what was intended.
The problem with this is that when you query for all the names of parameters in a patch ( that is, _get name_ into **live.object** for each _id), it is the _short name_ that is reported, not the scripting name. So if I'm trying to control the "E4L Source Panner" device from another Max device based on parameter name **Spread**, I can't actually set the value I want. 

I've attached some images that help illustrate this.

![get_names](https://user-images.githubusercontent.com/13511493/41204832-944bbebc-6c9e-11e8-9506-76f15a2f780d.png)
![spread ex1](https://user-images.githubusercontent.com/13511493/41204833-9474764a-6c9e-11e8-9a60-1ab252dbf1ec.png)
![spread ex2](https://user-images.githubusercontent.com/13511493/41204834-948af3f2-6c9e-11e8-96f9-6587f4b77e39.png)
Here's the M4L device that gets the parameters for a device.
[Live.API_tester.amxd.zip](https://github.com/EnvelopSound/EnvelopForLive/files/2088111/Live.API_tester.amxd.zip)

**Comment by mcslee** [comment]
Good catch - sorry about this, will fix in the next release!

**Comment by mcslee** [comment]
Fixed in a38d26ec2c9004f7157dbdd43148ea025083da9a
