### ISSUE TITLE
Need gain controls in Brownian Delay

### ISSUE THREAD

**Issue by mcslee** [EnvelopSound/EnvelopForLive#35]
With short delay times the output signal is super hot. Probably should have an input/output gain control on this one.

**Comment by roddylindsay** [comment]
added gain knob in db5c6de249896da41a24c3690039b91ed2f7366f

**Comment by mcslee** [comment]
Separated wet and dry: https://github.com/EnvelopSound/EnvelopForLive/commit/5bae0da871623ce687660b2445907465fe7fa855
