### ISSUE TITLE
Investigate CPU usage on delay boids example

### ISSUE THREAD

**Issue by mcslee** [EnvelopSound/EnvelopForLive#40]

**Comment by ramagottfried** [comment]
according to my tests:
* basic CPU usage without automation: ~11%
* with fast automation on every parameter: ~22%

so fast automation may increase the CPU usage by ~11%.

There is a lot of DSP processing in the device, so as with most heavy DSP processing situations, you may need to increase the signal buffer size and/or increase the driver error compensation to avoid clicks. 

I think we should make a note of this in the documentation in general, to warn people that when you are processing more channels it sometimes requires more CPU clock time per vector to process everything.
