### ISSUE TITLE
Make standardized 5.1 and 7.1 decoders with typical home theater speaker angles

### ISSUE THREAD

**Issue by mcslee** [EnvelopSound/EnvelopForLive#42]

**Comment by mcslee** [comment]
Added some real basic ones here: https://github.com/EnvelopSound/EnvelopForLive/commit/48d91d6dcd6d30aab9d886b42b07ed8e2f5987c5

They're not great since it's not a symmetric layout, but they'll do something until we can build better versions of these.

**Comment by msp** [comment]
Hey - thanks for a great project!

Curious about how these could be "better" (IRT your comment above) and have a few questions:

1) Digging into e4l decoder patches and the underlying ICST ambidecode~ help file it seems speaker config is always set on the same plane (i.e. elevation of zero). What if the speakers aren't on the same plane?

2) The available decoders set sensible angles for each speaker array but always assume a distance of 1 (i.e. each speaker is the same, maximum distance away from origin). If my performance space is a 5.1, non spherical cinema, should I measure speaker distance from some origin and add in distance values to a custom decoder?

Learning as I go here so thoughts welcome..

**Comment by mcslee** [comment]
Re: (1) - the speakers do not have to be on the same plane. Most of the examples just happen to do it this way since these are the common setups. But if you're using ambidecode~ you can set each channel to any azimuth, elevation, distance.

If you take a look inside https://github.com/EnvelopSound/EnvelopForLive/blob/master/patchers/remote/e4l.remote.midway.maxpat you'll see how this works. Open up the "coll Main" and you'll see the set of messages sent to ambidecode~ - each message is of the format "aed <channel-num> <azimuth> <elevation> <radius>".

To configure an ambidecode~ object, you just send it a sequence of these messages, one for each of your decoder outputs.

I suppose this also answers question (2) -  you can pass your own custom distances.

I'll note here that ambidecode~ is probably not the best choice of decoding algorithm for non-uniform arrays - it'll perform better the more uniform the layout is. But it's the easiest off-the-shelf one to use.

```
1, aed 1 158. 23. 1.;
2, aed 2 118. 29. 1.;
3, aed 3 62. 29. 1.;
4, aed 4 22. 23. 1.;
5, aed 5 -22. 23. 1.;
6, aed 6 -62. 29. 1.;
7, aed 7 -118. 29. 1.;
8, aed 8 -158. 23. 1.;
9, aed 9 158. 0. 1.;
10, aed 10 118. 0. 1.;
11, aed 11 62. 0. 1.;
12, aed 12 22. 0. 1.;
13, aed 13 -22. 0. 1.;
14, aed 14 -62. 0. 1.;
15, aed 15 -118. 0. 1.;
16, aed 16 -158. 0. 1.;
17, aed 17 158. -23. 1.;
18, aed 18 118. -29. 1.;
19, aed 19 62. -29. 1.;
20, aed 20 22. -23. 1.;
21, aed 21 -22. -23. 1.;
22, aed 22 -62. -29. 1.;
23, aed 23 -118. -29. 1.;
24, aed 24 -158. -23. 1.;
25, aed 25 90. 75. 1.;
26, aed 26 -180. 60. 1.;
27, aed 27 0. 75. 1.;
28, aed 28 -90. 60. 1.;
```
