### ISSUE TITLE
using a 360 ambi mic. in live 10.0.3

### ISSUE THREAD

**Issue by urantiani** [EnvelopSound/EnvelopForLive#48]
Hey 

It says som tutorials I need som endocer or something to make it work with files from ambimic recording  4 tracks . Do I neeed to roll back to live 10.0.2 to make it work ? 

Do I need some extra plug in or something to start working with 4 track ambi mic output files ? 

Thank you 
Nikolai

**Comment by urantiani** [comment]
if i file is recorded as a WAV poly file . How do I get it into Ableton at all ? Ableton does not wanto accept this kind of file

**Comment by urantiani** [comment]
adobe audition accepts is as a drag and drop easily . I guess ableton is not suited yet for WV poly files . Is there a workaround for this ? Do I have to record 4 tracks as seperate audio files then I guess ? 
Many questions hehe

**Comment by mcslee** [comment]
Hi there - Ableton does not *natively* support 4-channel files. However, when using E4L if you use the "E4L B-Format Sampler" device, it supports the playback of 4-channel WAV/AIFF files in either B-Format or AmbiX encoding.

I am not exactly clear what format your source material is. How are you producing this 4-track file to begin with? If it's in B-Format or AmbiX then you will be able to use it directly. If it is an A-format file, you will first need to convert it to a suitable format for E4L.

**Comment by urantiani** [comment]
hey :-)  i am learning this now in a stunt VR project .   I tried what you said infact and I noticed the sampler picked it up :-) I guess  its a B-format file then  I have recorded when linking 4 tracks together on the zoom F8 HD multitrack recorder . I installed a AMBEO A-B format converter plugin from sennheiser which works in Adobe and then I will try to convert that into a true stereo file (UHJ if I am not wrong) and then I can work easier in ableton live before syncing it togeter with the 360 cam film .  I was just hoping that I was free to work in ableton live with all this and then make music on top of the film audio from the ambi mic . but I am learning. 
Its just very new to me.
How would you use envelop then if you were working with VR film audio and adding 360 music bouncing it and then putting it together with the film again?

all the best and thank you for your time :-) 
Nikolai

**Comment by urantiani** [comment]
I am not sure I am making myself clear either since its a new language for me hehe

**Comment by urantiani** [comment]
the funny thing is you said it had to be transformed into B format . But the E4L B-format sampler accepted it without it going through the : AMBEO A-B format converter plugin from sennheiser

**Comment by mcslee** [comment]
> the funny thing is you said it had to be transformed into B format . But the E4L B-format sampler accepted it without it going through the : AMBEO A-B format converter plugin from sennheiser

If the file is in A-format, it will probably play back just fine, but the spatialization information might not be interpreted correctly. So while you'll hear some audio, it might not necessarily be the correct interpretation. This currently falls into the category of "trust your ears" and/or "you need to be sure what format your files in."

> How would you use envelop then if you were working with VR film audio and adding 360 music bouncing it and then putting it together with the film again?

With E4L, I would work using the B-Format Sampler to play back the ambisonics audio files, and when you're done composing your full mix, use the record functionality of the E4L Master Bus to export a file in 16-channel AmbiX or B-Format.

See: https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Master-Bus#recording for help with bouncing a master recording from the E4L Master Bus.
