### ISSUE TITLE
Missing instructions for JACK setup

### ISSUE THREAD

**Issue by schazers** [EnvelopSound/EnvelopForLive#5]
- should specify before starting JACK to disable the "auto-connect with physical ports" checkbox (it's enabled by default on OS X)
- there are currently no instructions for how to get the jack routes set-up. these instructions need to happen after everything else is set up and Live is running.
  1) in JACK's send ports column, select the "Live" row, then double-click the MAX row in JACK's receive ports column
  2) in JACK's receive ports column, select the "MAX" row, then double-click the "system" row in JACK's "connections" column

it may also be worth mentioning that this JACK patch can be saved and then re-loaded as a final step of the loading process each time

**Comment by roddylindsay** [comment]
the guide now has these instructions..thanks @schazers
