### ISSUE TITLE
7.1 output cascade output order

### ISSUE THREAD

**Issue by fred-dev** [EnvelopSound/EnvelopForLive#54]
Hi, amazing software, it really makes up for the very limited surround module with live 10. I have a few questions though, I am testing my setup (standard 7.1 array) and have noticed a few things when I do 7.1 decode. 

The first question might solve a lot of things. Which output order do you use for 7.1? I have an ITU standard setup (L, R, C, LFE, Ls. Rs, Lms, Lrs). Mostly it seems ok, but I get strange behaviour when I pan the signal to the rear of the array (so Ls and Rs channels with a 7.1 decode). IF this is not the layout is there a way to change the layout to standard ITU - I am running a series of presentations that are using 7.1 and have so far just used the ITU channel order.

Also I saw a post referencing a sharp volume jump in the centre position (https://github.com/EnvelopSound/EnvelopForLive/issues/26). I understand the logic behind the discussion. I would like to continue working in a standard 7.1 setup with Live and am wondering if there is a way to clamp the distance or limit it so it does not go to 0. I am not remaking your stuff, just dropping in the master bus and encoders (not that familiar with Max, or Live, but one of my students wanted to use Live in 7.1 and I am trying to support it.

**Comment by mcslee** [comment]
Hi Frederick - I believe our 7.1 decoder should be in the same order. Your notation is slightly confusing to me at the end... "Ls. Rs, Lms, Lrs" - was there a typo in Lms and Lrs?

Here's a screenshot of the 7.1 decoder patch:
<img width="1091" alt="Screen Shot 2019-04-17 at 5 09 14 PM" src="https://user-images.githubusercontent.com/597850/56328393-a4f11480-6133-11e9-94ba-14847f05bc2a.png">

Order is SMPTE: L, R, C, LFE, Ls, Rs, Lss, Rss

You can see the angles of each speaker - positive is clockwise, negative counter-clockwise
L (-30)
R (30)
C (0)
Ls (-120)
Rs (-120)
Lss (-90)
Rss (-90)

Does this roughly match your speaker layout?

> I would like to continue working in a standard 7.1 setup with Live and am wondering if there is a way to clamp the distance or limit it so it does not go to 0.

Sure, if you want to make "0" distance impossible, one idea would be to put the device in an effect rack and assign a macro knob to the radius control with a limited range. Screenshot attached - let me know if that's not clear.

<img width="571" alt="Screen Shot 2019-04-17 at 5 12 50 PM" src="https://user-images.githubusercontent.com/597850/56328488-10d37d00-6134-11e9-8eed-78249bb65824.png">
