### ISSUE TITLE
Laptop Output

### ISSUE THREAD

**Issue by fredmjs** [EnvelopSound/EnvelopForLive#56]
Hey Guys, thanks for your patience but I'm doing a listening session for 25 people surrounded with 4 speakers and sub. Can I just do a stereo output from my laptop and how should I split between speakers. Could I add a  USB sound card for 2 more signals so each speaker has it's own channel? Thanks again.

**Comment by mcslee** [comment]
Hi Fred - a stereo laptop speaker output is not sufficient for surround sound. If you're using 4 speakers and a sub, you are either going to need 4 outputs (and merge them all to the sub), or ideally 5 outputs (with a dedicated output for the sub). There is a "Quad" decoder in the default E4L package that could be suitable for this scenario.
