### ISSUE TITLE
Source Panner and Master Bus Routing Not Functioning Correctly

### ISSUE THREAD

**Issue by amw26** [EnvelopSound/EnvelopForLive#58]
Hi,

Thanks for the great software. I've used E4L before and it has worked perfectly well. However, with this new quad piece I'm working on, the source panner, and all other E4L panning devices, are not panning correctly. When I pan towards L, R, Ls or Rs the resulting direction of audio in the sound-field is not corresponding to how I am panning (e.g. when I pan towards L, the audio comes mainly from the Ls speaker and when I pan towards R, the audio comes mainly from the Rs speaker, etc). When I test a sound through each speaker using discrete multichannel panning, the sound comes out of the correct speaker, but the panning seems completely "off" with the E4L panners. In a way, it seems kind of inverted as the sound-field appears flipped at points.

I have checked all my output routing and my audio cables are definitely corresponding with my audio interface correctly: 1=L, 2=R, 3=Rs, 4=Ls. 

I've attached images of my source panner and master bus.

I'm running on MacOS Mojave 10.14.5, Ableton Live Suite 10.1 and I'm using a Focusrite Scarlett 6i6 interface. I've re-downloaded the latest driver for the interface and made sure accessibility is enabled for the interface in the Privacy section of System Preferences—but still having the same issue. I've also tried using a MOTU interface but the issue persists.

Would be great if someone could help with this as the software was a great tool before this happened.

<img width="363" alt="Screenshot 2019-07-01 at 20 59 08" src="https://user-images.githubusercontent.com/52426894/60464237-e038b500-9c45-11e9-9e5c-24181d88d9f8.png">
<img width="486" alt="Screenshot 2019-07-01 at 20 59 55" src="https://user-images.githubusercontent.com/52426894/60464244-e464d280-9c45-11e9-916a-9d8800404a82.png">
<img width="363" alt="Screenshot 2019-07-01 at 21 24 28" src="https://user-images.githubusercontent.com/52426894/60464518-af0cb480-9c46-11e9-9970-1e15ebd566b6.png">

**Comment by mcslee** [comment]
Hi there - sorry to hear about this issue. It looks to me like you do have everything configured correctly. The only minor issue I'm seeing is that it looks like you have duplicated the 5/6 Output Routing on the E4L Master Bus to your soundcard 3/4 outputs. But that shouldn't cause any issue here, as those outputs should just be silent on the Quad decoder.

I'm curious - can you try some of the other decoders (perhaps the Octo) and test if that seems to route properly with your speakers (would just be 4 of them, but that'd be enough to get the idea).

I'm curious if this is some kind of routing issue within Ableton, or if it's specific to the Quad decoder. Do any other decoders work okay for you? Does the Binaural work properly?

> Would be great if someone could help with this as the software was a great tool before this happened.

Did the Quad decoder ever work properly for you? Or were you working with another decoder previously?

**Comment by amw26** [comment]
Hi, 

Thanks for getting back to me.

I've tried with all the other decoders and they all seem strange and not panning correctly–including the Octo decoder. Binaural seems to work better (I think) but there are still some strange things happening when I move the panner. 

The quad panner did work perfectly the last time I used it for a piece, which was back between October/November 2018 to February 2019.

I've now tried it on another separate laptop with my 2nd authorisation of Ableton Live 10 but the same issue persists—even on a separate laptop.

Could it perhaps be that I need to purchase Max 8 as well? I have only purchased Ableton Live 10, with Max 8 bundled in with it. Could this be what is crippling it?

**Comment by amw26** [comment]
I seem to have sorted it. 

I had remembered that last time I used the software I had put the master bus on an audio or MIDI track, but I must have misremembered as it now works when I put it on a return track.

Really pleased that it works now!

Thanks again for getting back to me as well.

**Comment by mcslee** [comment]
Yeah the E4L Master Bus *should* be on a regular Audio track. Specifically, it should not be on the Ableton Master track, that will cause problems. A return track probably works fine as well. Glad this sorted it out.
