### ISSUE TITLE
Quad Output Instructions

### ISSUE THREAD

**Issue by fredmjs** [EnvelopSound/EnvelopForLive#61]
Hey guys, I would appreciate if you would point me in the right direction. I've installed Ableton and and Envelop on my Intel NUC with an internal soundcard and external USB sound card. I want to send a stereo signal through quad panner and output 4 channels. I'm needing a basic step by step for an event. Thanks.

Here's what my sound guy is asking:  Do you own or can you you rent/borrow a soundcard/interface that you can test beforehand to make sure that you can send me 4 separate channels of audio to my mixer? Then I can sum those to a mono signal for the sub and send them separately to the speakers as well?

**Comment by mcslee** [comment]
Hi Fred - to do this you will need one soundcard that has at least 4 outputs. I'm not sure what your external USB sound card is.

In Ableton, select the soundcard with 4+ channels as the output device (in the attached example, I'm using a K-Mix).  Click on "Output Settings" and ensure that outputs 1/2 and 3/4 are enabled.

Then, in the E4L Master Bus device, you'll select the "Quad" option from the dropdown and assign outputs 1/2 and 3/4, as shown. You will want to have "Monitor 1+2" disabled. This will send Envelop's output to the four outputs of the soundcard.

Good luck!

<img width="361" alt="Screen Shot 2019-10-09 at 12 42 11 PM" src="https://user-images.githubusercontent.com/597850/66474818-598c4300-ea92-11e9-8d0e-c4d6cf59873c.png">
<img width="1006" alt="Screen Shot 2019-10-09 at 12 40 42 PM" src="https://user-images.githubusercontent.com/597850/66474819-598c4300-ea92-11e9-8e6e-6229dc4f546c.png">
