### ISSUE TITLE
E4L Master bus – recording a multichannel track results in a text file

### ISSUE THREAD

**Issue by tre5e** [EnvelopSound/EnvelopForLive#63]
Hello, 

I am trying to render an ambisonic quad mix into a multichannel wav or aiff-file. When I choose 4 channels, ambix/b-format, arm the master bus and play the project, the file for some reason is not saved as neither an aiff or wav file, but always as a text document, regardless of what I choose as a file format. What am I doing wrong? 

PS! I am completely new in this ambisonic world, so I am sorry if this is very basic. 
<img width="375" alt="Screenshot 2020-01-18 at 23 31 02" src="https://user-images.githubusercontent.com/60048923/72671452-ad6fd600-3a4a-11ea-92bf-8a466f9f2628.png">

**Comment by mcslee** [comment]
Have you tested manually changing the extension on the file? I'm not sure why it would have the wrong suffix, may just be a weird thing with the file save prompt dialog. But it looks like you are setting things up properly. Let me know if the file work if you manually rename it to have the right file type ending...

**Comment by tre5e** [comment]
YES! When manually changing the suffix when saving the file it works! THANK YOU! I must've spent four hours yesterday not understanding what on earth I was doing wrong.

**Comment by mcslee** [comment]
Super annoying, sorry about that! No clue why it would leave the suffix off on your system...
