### ISSUE TITLE
Export multichannel mix

### ISSUE THREAD

**Issue by badgic** [EnvelopSound/EnvelopForLive#64]
Hello, few months ago with your advices I was able to easily export a binaural mix of a multichannel piece. I wonder if there is way to capture the multichannel when exporting/mixing down the session ( for speakers not headphones, capturating the metadata) can’t figure it out yet. Thanks, axelle

**Comment by mcslee** [comment]
Hi - if you want to make a recording of the ambisonics-encoded signal, follow the instructions in the Recording section of the E4L Master Bus device:
https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Master-Bus#recording

**Comment by badgic** [comment]
yes I saw that, was hoping there would be another way to export/render the data. Could you please let me know witch ambisonic software is compatible to read the rendered file? Many thanks

**Comment by mcslee** [comment]
The recorded files using the E4L Master Bus are multi-channel WAV/AIFF files, encoded in Ambisonics format. Most Ambisonic softwares should be able to play this back. The software will need to include a decoder if you wish to translate from Ambisonics spatial audio into discrete speaker channels.

I'm not sure what you mean by "capturing the metadata." An ambisonics file is a complete representation of a 3-D sound field. It does not typically include metadata about speaker configurations or discrete sound sources.

Maybe you can describe the higher-level goal you are trying to accomplish here and I can offer some guidance?

**Comment by badgic** [comment]
Thanks Mark, sorry for asking an obvious question. I wasn’t sure if the ambisonic file would have all the data, including volume automation as with the binaural had to do a little trick. But that’s obviously différent as it render directly from the E4L master bus. 
As I have never done it before do you have any suggestion on the ambisonic software to decode?

**Comment by mcslee** [comment]
You can decode using Envelop. If you've exported a file from the E4L Master Bus, you can play it back using the https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-B-Format-Sampler

Then use the decoder section in the E4L Master Bus to select your speaker configuration:
https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Master-Bus#decoding

Alternately, you may create a custom decoder if you have a special or irregular speaker layout, which is a bit more advanced:
https://github.com/EnvelopSound/EnvelopForLive/wiki/Implementing-a-Custom-Decoder

**Comment by badgic** [comment]
Thank you Mark, it.s very useful, I will look in details.
