### ISSUE TITLE
Midi circle 

### ISSUE THREAD

**Issue by kevin815953** [EnvelopSound/EnvelopForLive#65]
![未命名](https://user-images.githubusercontent.com/60833130/74095383-9fcddd80-4b2a-11ea-9944-97bb6f70adab.jpg)

I wonder how can I set the midi control to Azim, when I turn to 180 degree and it can set to 0 degree, that I can make it circle.

**Comment by mcslee** [comment]
To my knowledge this is unfortunately not possible. I don't think Ableton has any explicit support for this type of "wrap-around" parameter. You might be able to construct some more advanced MIDI macro or script to handle it. I don't think this will be achievable with the basic MIDI mapping. Sorry about this.
