### ISSUE TITLE
multichannel mixing method and length

### ISSUE THREAD

**Issue by kevin815953** [EnvelopSound/EnvelopForLive#66]
I wonder if the best way to export/render my multichannel mixing is recording by the master bus then when I performance I play it back by B-format Sampler.

Because I have a try to performance the show that will make the QUAD sound, I will mix the PGM then play it on the show, so I have another question, how long is the recording I can do. my show's length is about 20min. 
does anybody try this before?

Thanks.

**Comment by mcslee** [comment]
Recording your mix and playing it back with the B-Format sampler is definitely a reasonable approach, we have done this ourselves before. A 20 minutes recording should be fine. Let us know how it goes!
