### ISSUE TITLE
No routing for B-Format audio sources

### ISSUE THREAD

**Issue by alessiomastrorillo** [EnvelopSound/EnvelopForLive#70]
Hi.
It looks like there is no way to route a 1-order ambisonics source (with the w,x,y,z, channels) into the master bus.

**Comment by mcslee** [comment]
Hi Alessio - you are correct. Ableton is by its nature a fundamentally stereo program - all native tracks and buses can only carry two channels of audio. This is why E4L uses the special devices to route multichannel Ambisonics audio to the E4L Master Bus device.

If you want to export a 1st-order AIFF file, you can do so using the recording feature of the E4L Master Bus device. Instructions on that procedure are available here: https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Master-Bus#recording

Hope this helps!

**Comment by alessiomastrorillo** [comment]
Thanks. 
We could put the four encoded tracks into four Live channels, group them together and send them into the Master Bus for final decoding... they're already encoded, it's just a matter of routing them into the bus.

**Comment by mcslee** [comment]
Unfortunately that won't work, when you group tracks in Ableton, that is just a group of stereo buses, and Ableton automatically sums the signals together. They are not sent separately to the receiving bus, there would be no way to separate back out the WXYZ.

Maybe I am not understanding what you are trying to do here. Do you have a pre-existing B-format file that you are trying to play back using E4L? In this case, you can use the E4L B-Format Sampler device to play back this file, and send it to the E4L Master Bus decoder.

There are instructions on that device here:
https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-B-Format-Sampler

Maybe that will accomplish what you are trying to do?

**Comment by alessiomastrorillo** [comment]
![Screen Shot 2020-11-22 at 16 44 30 (2)](https://user-images.githubusercontent.com/63250257/99908774-b1acf580-2ce4-11eb-8cf8-8951f3cb1dbb.png)
<img width="467" alt="Screen Shot 2020-11-22 at 16 44 30" src="https://user-images.githubusercontent.com/63250257/99908775-b376b900-2ce4-11eb-8b6c-8d96fca3105d.png">

I'm posting screenshots, so it's clear what I meant. I use to record in b-format with classic fig-8 and omnidirectional mics. The three or four channels, depending on mic setup, are routed into Live. Then I mix them with E4L vst of my creation, that's why I asked because I've already done that and could be a useful plus for your package as well.

**Comment by alessiomastrorillo** [comment]
I suppose the channel order is w,x,y,z and so on, on plugout~, so I've patched the four plugin~ straight into them for the Master Bus to decode.

**Comment by mcslee** [comment]
Ah, thanks for the explanation, I understand what you're trying to do now. If you already have these B-format tracks broken out, then you can actually route them directly into the E4L Master Bus device without needing to use an additional intermediary device. The 3rd order ambisonics signal goes into inputs 3-18 of the E4L Master Bus device.

Note that E4L internally uses AmbiX format with ACN channel order and weighting is SN3D. This is slightly different from B-format in Furse-Mulham: https://en.wikipedia.org/wiki/Ambisonic_data_exchange_formats#Component_ordering

ACN ordering is W, Y, Z, X - you'll just need to check which weighting whatever program you have used to create the B-format files used. There are some plugins from Rode FYI that do many of these conversions: https://www.rode.com/soundfieldplugin#footer_download

Here is a max patch that shows conversion from B-format FuMa to AmbiX:
https://github.com/EnvelopSound/EnvelopForLive/blob/master/patchers/ambix/e4l.ambix.frombformat.maxpat

If you have 1st-order B-format content in FuMa, all you would need to do is put the channels in correct order and apply a +3dB gain to the W channel. You can use a "Utility" device to pan the W channel hard left (so it goes to input 3), the Y channel hard right (so it goes to input 5), Z hard left (input 6) and X hard right (input 7). You can see an example of that on the screenshot below.

I think this should achieve what you are looking for - good luck!

<img width="1151" alt="Screen Shot 2020-11-22 at 4 08 29 PM" src="https://user-images.githubusercontent.com/597850/99921171-870b6e80-2cdd-11eb-8a71-4179d8b54892.png">

<img width="890" alt="Screen Shot 2020-11-22 at 4 11 31 PM" src="https://user-images.githubusercontent.com/597850/99921173-88d53200-2cdd-11eb-8d1e-c38a493e3b39.png">

**Comment by alessiomastrorillo** [comment]
This is it! Thanks Mark!

**Comment by alessiomastrorillo** [comment]
Last question, just out of curiosity: is the Stereo Decoder UHJ?

**Comment by mcslee** [comment]
Great - glad this works! Our Stereo Decoder is not UHJ. If you know of an open source implementation of UHJ though, it's something that we could potentially integrate.

**Comment by alessiomastrorillo** [comment]
There is, but it only conveys information from first-order coordinates. Since we are working with 3rd order Ambisonics, we should keep spatial information from all spheric harmonic.

**Comment by alessiomastrorillo** [comment]
I've done it, would you like to test it out?

**Comment by mcslee** [comment]
Yes, if you'd like to share it, that would be great if we can take a look, thanks!
