### ISSUE TITLE
multiple  E4L Master Bus for managing multiple IEMs 

### ISSUE THREAD

**Issue by zbynekdrlik** [EnvelopSound/EnvelopForLive#71]
I am interested to have multiple  E4L Master Bus in one Ableton and choose which source panner use which Master Bus. Is it possible?

**Comment by mcslee** [comment]
Unfortunately this is not possible with the current version, the multi-channel routing is done automatically by the software and it currently operates on the assumption that there is a single E4L Master Bus device. Having the ability to create multiple distinct Ambisonics buses is something that we may consider for a future version - but the behind-the-scenes routing gets a bit complex. So we have generally erred on the side of simplicity to try to keep the software as lightweight and reliable as possible.

Sorry it's not possible, hope this helps!
