### ISSUE TITLE
Not working on Apple M1 / Sillicon + Ableton Live 11.1 Beta

### ISSUE THREAD

**Issue by vespakoen** [EnvelopSound/EnvelopForLive#77]
Just reporting here that the upstream "Ambisonics" package is not compiled for arm64 / Apple M1 / Apple Silicon yet.
I already sent an email to them about it, and though i'd drop it here as well.

<img width="1210" alt="Screenshot 2021-10-29 at 21 34 07" src="https://user-images.githubusercontent.com/876117/139493050-2e750143-ce0a-4992-9d74-36b4d3f6cc14.png">
<img width="1210" alt="Screenshot 2021-10-29 at 21 38 30" src="https://user-images.githubusercontent.com/876117/139493064-e47542ad-308e-4a07-aa47-8bb41023fd5e.png">

**Comment by mcslee** [comment]
Hi Koen - thank you for the report. I am not surprised to see this, we haven't started any real testing on M1 builds yet, and to be honest I don't expect that this will be likely to work for quite a while. It will require rebuilding all of the externals that are used, which are quite a few. If you do any additional work/testing with this, please do feel free to post updates - helpful to at least know the state of things. Cheers!

**Comment by mcslee** [comment]
It's in the queue! No progress just yet, but the good news is that I've checked the libraries we depend upon and I believe the majority of them have M1 builds available now, so the core panners should all be upgradeable.

Will post here when there's a build to share. Cheers!

**Comment by mcslee** [comment]
FYI - a preliminary pre-release with Apple Silicon support is now available for testing: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.3.4

Seems to be working well on my system. If anyone has a chance to test, please let me know how it goes.

**Comment by mcslee** [comment]
Quick update - we have release 11.3.11 out now with some more new devices + fixes in addition to the Apple Silicon compatibility: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.3.11
