### ISSUE TITLE
B Format Conv Reverb - Not hearing a difference when I use my own IR files

### ISSUE THREAD

**Issue by jinnandtonic** [EnvelopSound/EnvelopForLive#78]
I've tried drag/dropping multiple different IR wav files into the device, they seem to load fine but when I play sound it always sounds like the default impulses from when the device is loaded.  If I'm using my own IR files do they need to be formatted differently?  Thanks

**Comment by mcslee** [comment]
Hi there - sorry to hear you are having this issue. I tested on my machine and drag/drop replace seemed to work okay, what platform and version of Live and E4L are you running?

If drag/drop does not work you may also try clicking manually the W/X/Y/Z buttons to the left of the filenames and replacing the files one by one.

The format should be 4 identical length WAV files, all in MONO. There are example files in this folder:
https://github.com/EnvelopSound/EnvelopForLive/tree/master/media/ir

Either of those sets of files should work. If you test replacing with those files do you hear a difference?

**Comment by jinnandtonic** [comment]
I'm on a 2020 Mac Mini with M1.

I think it's the *identical length* that was the problem.  I was trying to mix-and-match a variety of IRs to get some intentionally weird results but they were all of different length.

Thanks for responding!
