### ISSUE TITLE
E4L Mono Panner - Archor SYNC to SONG POSITION

### ISSUE THREAD

**Issue by hems** [EnvelopSound/EnvelopForLive#81]
One thing i noticed on the E4L Mono Panner is that when when running the CYCLE in SYNC it won't STOP and START the SYNC together with the DAW timeline so every time i start a song it starts in a different position.

Ideally the LFO should be reset with the song tempo so i can always reproduce the same position on the sounds in relation to my DAW timeline.

That would be really sweet and help me avoid having extra LFOs on my DAW to achieve syncronisation.

Thank You

**Comment by mcslee** [comment]
Yep, good call, fully agreed this would be much better if synced to the grid. Will put this on the TODO list, thanks!

**Comment by hems** [comment]
> Yep, good call, fully agreed this would be much better if synced to the grid. Will put this on the TODO list, thanks!

probably should be applied to all the other SYNC on cycles i guess? sorry i was lazy and didn't list all the devices that have this function.

**Comment by mcslee** [comment]
Ah totally, that's a good suggestion too. I'll toss it on the thread just
so he has a short-term fix if he wants it.

**Comment by mcslee** [comment]
Yes definitely, this applies to a bunch of devices with that LFO implementation, I will apply the fix to all of them in the same way.

FYI in the short term @willits noted another solution he uses to fix this:
> Heads up if this helps, I solve this problem by automating the LFO to be on / off in the arrangement view.

That's not ideal to have to do, but if you need a short-term solution to get reproducible results on your project, you can use that hack for the time being.

**Comment by hems** [comment]
> > Heads up if this helps, I solve this problem by automating the LFO to be on / off in the arrangement view.
> 
> That's not ideal to have to do, but if you need a short-term solution to get reproducible results on your project, you can use that hack for the time being.

thanks for the heads up, that's a great hack! @mcslee / @willits !

At the moment I went around it by using Ableton's LFO, which isn't a terrible situation to be honest but i thought would be worth noting it here.

**Comment by mcslee** [comment]
This is fixed by: https://github.com/EnvelopSound/EnvelopForLive/commit/b3f010f924975979f1245cbb320b06ccc2b43c40

Available as part of the 11.0.1 release: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.0.1

Applies to Mono Panner, Stereo Panner, and Quad Panner
