### ISSUE TITLE
AuraVerb is not working on Windows 10?

### ISSUE THREAD

**Issue by hems** [EnvelopSound/EnvelopForLive#82]
Unfortunately AuraVerb is not working on Windows 10 :(

I'm running version 11, here is a screenshot of the max console... i guess those are externals that might not be available for PC or is it me who should have installed but didn't?

![image](https://user-images.githubusercontent.com/27327/148453153-ce17a7c2-6232-4fea-a258-6f70e11d0b87.png)

**Comment by mcslee** [comment]
Thanks for the heads up. I think we may have failed to bundle those externals in with the release of version 11.

Though you should be able to grab them here:
https://github.com/EnvelopSound/EnvelopForLive/tree/master/externals/AuraVerb

The mxe/mxe64 files ought to fix this if you can get them in your Max path. I will ensure these are properly bundled on a future release (I will just note for the record that we don't *officially* support Windows, but it does seem to work fine on most systems).

**Comment by hems** [comment]
> Though you should be able to grab them here: https://github.com/EnvelopSound/EnvelopForLive/tree/master/externals/AuraVerb
> 
> The mxe/mxe64 files ought to fix this if you can get them in your Max path. 

that did the trick

> I will ensure these are properly bundled on a future release

awesome

> (I will just note for the record that we don't _officially_ support Windows, 

I don't officially support Windows too, but I have to use it at least until i can replace my soundcard by a new soundcard supported on the new OS X :(

Apple dropped the support from my interface so Windows 10 is all I have now.

> but it does seem to work fine on most systems).

From my experience it has been really stable on small ableton projects.. Once i start playing around with tons of VSTS and Envelop devices Ableton is crashing sometimes.. Not sure if Envelop is to blame.

Anyway i'll keep you guys up to date and help test things on Windows in case you need some help with that, it's the least i can do as a Windows user.

Thanks again for such fast replies and amazing support, you guys are the best.


BTW: I clicked the "**Donate**" button on your website but the DONATE link ( https://charity.gofundme.com/o/en/donate-widget/17055 )  is broken, no wonder you guys haven't received anything recently : D

drop me your paypal or ethereum address and i'll send you guys a few beers.

💘

**Comment by hems** [comment]
ACTUALLY,

it only works when i open the PATCH for editting, like this:

![image](https://user-images.githubusercontent.com/27327/148455272-bda45ff8-bedb-4cf2-a76f-e48bb9e77e02.png)


If i live it inline  or "docked" on Ableton's UI, like this:

![image](https://user-images.githubusercontent.com/27327/148455312-6bfc8853-718a-4938-8da1-11fc16dcd04b.png)

 it doesn't work even tough the externals are now on the path.

**Comment by mcslee** [comment]
This should now be fixed in the version of E4L AuraVerb that is included with the ZIP bundle for the 11.0.1 release, available here: https://github.com/EnvelopSound/EnvelopForLive/releases/tag/11.0.1
