### ISSUE TITLE
Is it possible to produce immersive music using a sound bar?

### ISSUE THREAD

**Issue by fehmi** [EnvelopSound/EnvelopForLive#84]
I'm not sure if it's the right place to issue this but I'm out of luck with Google search. I'm thinking about to buy Sennheiser Ambeo for this. Envelop for Live is working great with my headphones (Beyerdynamic T5) I wonder if it works with the same way with the Sennheiser sound bar?

**Comment by mcslee** [comment]
Hi Fehmi - you can definitely work with a soundbar, though the experience will not really be like headphones and will depend heavily upon the acoustics in the room where you have the soundbar placed.

For a soundbar I would recommend working with a 5.1 or 7.1 decoder, as most soundbars these days support those formats. This will likely work a bit better than binaural, which is really designed for headphones and may introduce strange phase issues when played back on an in-room system. (Though sometimes this is interesting in a more experimental way, so feel free to explore).

Best of luck with it!
