### ISSUE TITLE
Envelop4live

### ISSUE THREAD

**Issue by Georgina111** [EnvelopSound/EnvelopForLive#91]
When i listen to my Live set with the Ambisonic E4L plugins all is well, but when i try to make a bounce to either 3rd order binaural, binaural or stereo format, the right channel looses all it's fidelity.. so instead of going hard right the sound just stays in the centre. Any format i choose is the same story.. ?

**Comment by mcslee** [comment]
What process are you using to create a bounce. Are you using the normal Ableton Export Audio/Video option? While running the Binaural decoder?

What you are describing sounds a bit like what would happen if you were actually exporting Ambisonics-encoded data.

Can you send a description of your export process and screenshots of how you have the E4L Master Bus configured while doing this?

**Comment by Georgina111** [comment]
Hi Mark and thanks.. 

This is my E4L master bus settings.. I Pressed the red button to then name the track and the started playing the set. 




This is recording I made.. 

best,
Georgina

**Comment by Georgina111** [comment]
﻿
Hi Mark and thanks.. 

This is my E4L master bus settings.. I Pressed the red button to then name the track and the started playing the set. 




best,
Georgina

**Comment by Georgina111** [comment]
Sorry, am new to git hub... here's the image of my settings
![image0](https://user-images.githubusercontent.com/114779197/193364127-98b3c055-5360-4767-843c-a4969decb07b.jpeg) I Pressed the red button to then name the track and the started playing the set.

**Comment by Georgina111** [comment]
Ok, i realise what i have done .. I mistakenly thought to export the files from the masterbus plugin... i just bounced the track down as usual and it works perfectly..

**Comment by Georgina111** [comment]
And thank you for your help

**Comment by mcslee** [comment]
Great - glad you got this sorted out.

Yes, the export feature on the E4L Master Bus is for exporting the encoded ambisonics signal, before it goes through the decoder. If you want to export the results of the binaural decode, then the normal Ableton render flow should work just fine.

If you want to export many channels from a multi-channel decode (e.g. quad/octo/etc.) there are some instructions here:
https://github.com/EnvelopSound/EnvelopForLive/wiki/E4L-Export-Utility

Happy mixing!
