### ISSUE TITLE
E4L Master Bus - hb1_to_binaural~

### ISSUE THREAD

**Issue by dnlfbr** [EnvelopSound/EnvelopForLive#98]
The Binaural output Mode of the E4L Master Bus doesn't work on Apple Silicon processor.
The hb1_to_binaural~ object (used for Binaural mode) is not working.
I've tried to recompile it (source: https://bitbucket.org/ambidecodertoolbox/adt/src/optimizer/faust/hb1_to_binaural.dsp)
 to a .mxo file on the Faust IDE, but still It doesn't work (error: hb1_to_binaural~: could not load due to incorrect architecture).
Any support is appreciated!

**Comment by mcslee** [comment]
Yep, thanks for the report - this is on our todo list for Apple Silicon upgrade. The external will definitely need to be rebuilt.

**Comment by mcslee** [comment]
This can now be used via faustgen~ on Apple Silicon:
https://github.com/EnvelopSound/EnvelopForLive/commit/c3d7bbb8add02d179f559aa7c412108327b83404
