### ISSUE TITLE
Master Bus not receiving audio, and unable to see output channels

### ISSUE THREAD

**Issue by iorobertob** [EnvelopSound/EnvelopForLive#99]
macOS 10.12.6
Ableton 9 suite

Master bus is not receiving audio from source panner, nor is it seeing available output channels in the dropboxes, no matter wha output device is selected in preferences.

**Comment by mcslee** [comment]
Hi Roberto - unfortunately we do not support Ableton 9, you will need to upgrade to at least version 10, but preferably 11, in order to use the latest E4L tools. Sorry about this.
